# Site settings
name: Todd Develops.
title: Very Much Blogging. Such Code. 
email: toddguerra@gmail.com
description: "Todd M Guerra is an Adobe AEM developer who plays with all sorts of things in his spare time."
baseurl: "http://gutsy.github.io/"
url: "http://gutsy.github.io/"

# Build settings
markdown: kramdown
permalinks: pretty
